name: Feature request
description: Suggest an idea for this project.
title: "[feat]: "
labels: ["enhancement"]
assignees:
  - tprouvot
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      description: By submitting this request, you agree to perform the following checks.
      options:
        - label: I've searched in the [documentation](https://tprouvot.github.io/Salesforce-Inspector-reloaded/) and did not found anything related to the feature I'm about to request.
          required: true
        - label: I've read the [release note](https://github.com/tprouvot/Salesforce-Inspector-reloaded/blob/releaseCandidate/CHANGES.md) and the one I'm about to create is not already developed.
          required: true
  - type: textarea
    id: describe
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: textarea
    id: wish
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
    validations:
      required: true
